// ── Domain types ────────────────────────────────────────────────────────────
//
// These interfaces mirror the Postgres table columns in `public` schema 1:1.
// Generated by hand from information_schema.columns on 2026-04-23.
//
// Philosophy:
//   - One canonical type per DB row shape.
//   - UI consumers that want a narrow subset use `Pick<Policy, 'id' | 'insurer' | ...>`.
//   - Do not add UI-only fields here. Compute/derive those at the render site.
//
// When a DB migration changes schema, update this file at the same time.
// The supabase/migrations/ directory tracks the SQL; this file tracks the TS.

// ── Policy (maps to public.policies) ─────────────────────────────────────

export interface Policy {
  id: string
  client_id: string
  ifa_id: string

  // Denormalized carrier / product info
  insurer: string | null
  type: string | null
  policy_number: string | null
  product_name: string | null

  // Financials
  premium: number | null
  premium_frequency: string | null  // 'annual' | 'monthly' | 'quarterly' etc; default 'annual'
  sum_assured: number | null

  // Dates
  start_date: string | null         // date
  renewal_date: string | null       // date

  // Lifecycle
  status: string | null             // 'active' | 'lapsed' | 'cancelled' | 'pending'; default 'active'

  // Free-text
  notes: string | null

  // Timestamps
  created_at: string | null
  updated_at: string                 // NOT NULL as of Batch 21
}


// ── Alert (maps to public.alerts) ─────────────────────────────────────────
//
// Alerts is a catch-all notifications/events table. Conceptual types in
// the `type` column include: 'claim' | 'renewal' | 'document' | 'payment'
// | 'client_message'. Not enforced at the DB level — add a CHECK constraint
// when the set stabilises.

export interface Alert {
  id: string
  client_id: string | null
  ifa_id: string

  type: string
  title: string
  body: string | null

  priority: string | null      // default 'medium'
  status: string | null        // default 'open'
  resolved: boolean | null     // default false

  created_at: string | null
  updated_at: string           // NOT NULL as of Batch 21
}


// ── Holding (maps to public.holdings) ─────────────────────────────────────

export interface Holding {
  id: string
  client_id: string
  ifa_id: string

  // Product identity
  product_type: string             // NOT NULL per DB
  product_name: string             // NOT NULL per DB
  provider: string                 // NOT NULL per DB
  platform: string | null
  isin: string | null
  currency: string                 // NOT NULL per DB, default 'SGD'

  // Position
  units_held: number | null
  avg_cost_price: number | null
  last_nav: number | null
  last_nav_date: string | null
  current_value: number | null
  distribution_yield: number | null

  // Classification (Batch 8)
  asset_class: string | null
  asset_class_other: string | null
  geography: string | null
  geography_other: string | null
  sector: string | null
  sector_other: string | null

  // Lifecycle
  risk_rating: string | null
  suitable_for: string | null
  inception_date: string | null
  last_reviewed_at: string | null

  // Free-text
  notes: string | null

  // Timestamps
  created_at: string               // NOT NULL per DB
  updated_at: string               // NOT NULL per DB, triggered by Batch 21
}

// ── UI types (ClientDetailPage) ─────────────────────────────────────────────

export interface Message {
  id: string
  role: string
  content: string
  created_at: string
}

export interface Conversation {
  id: string
  status: string
  messages: Message[]
}

export interface CoverageItem {
  key: string
  label: string
  hasCoverage: boolean
  insurer: string | null
}

export interface TimelineItem {
  date: string
  text: string
  type: string
}

export interface Metric {
  label: string
  value: string
  subtitle?: string
}

export interface ClientData {
  id: string
  name: string
  company?: string
  type: string
  tier: string
  whatsapp?: string
  email?: string
  birthday?: string
  address?: string
  notes?: string | null
  nok_name?: string | null
  nok_relationship?: string | null
  nok_phone?: string | null
}

export interface Props {
  client: ClientData
  policies: Policy[]
  conversations: Conversation | null
  claims: Alert[]
  metrics: Metric[]
  birthdayDisplay: string
  coverageAnalysis: CoverageItem[]
  timeline: TimelineItem[]
  connectionStatus: 'connected' | 'pending' | 'not_connected'
  dob?: string | null
  notes?: string | null
  nok_name?: string | null
  nok_relationship?: string | null
  nok_phone?: string | null
  calculatedTier: string
  ifaId: string
  ifaName: string
  holdings: Holding[]
}

