// ── Domain types ────────────────────────────────────────────────────────────
//
// These interfaces mirror the Postgres table columns in `public` schema 1:1.
// Generated by hand from information_schema.columns on 2026-04-23.
//
// Philosophy:
//   - One canonical type per DB row shape.
//   - UI consumers that want a narrow subset use `Pick<Policy, 'id' | 'insurer' | ...>`.
//   - Do not add UI-only fields here. Compute/derive those at the render site.
//
// When a DB migration changes schema, update this file at the same time.
// The supabase/migrations/ directory tracks the SQL; this file tracks the TS.

// ── Policy (maps to public.policies) ─────────────────────────────────────

export interface Policy {
  id: string
  client_id: string
  ifa_id: string

  // Denormalized carrier / product info
  insurer: string | null
  type: string | null
  policy_number: string | null
  product_name: string | null

  // Financials
  premium: number | null
  premium_frequency: string | null  // 'annual' | 'monthly' | 'quarterly' etc; default 'annual'
  sum_assured: number | null

  // Dates
  start_date: string | null         // date
  renewal_date: string | null       // date

  // Lifecycle
  status: string | null             // 'active' | 'lapsed' | 'cancelled' | 'pending'; default 'active'

  // Free-text
  notes: string | null

  // Timestamps
  created_at: string | null
  updated_at: string                 // NOT NULL as of Batch 21
}
